#!/bin/sh

set -e

OUTPUT_THEME_NAME=${1:-gtkreated}

config_home=${XDG_CONFIG_HOME:-$HOME/.config}
data_home=${XDG_DATA_HOME:-$HOME/.local/share}
SRC_PATH="$data_home/gtkreate"
CONFIG_PATH="$config_home/gtkreate/gtkreaterc"
DEST_PATH_ROOT="$HOME/.themes"
DEST_PATH="$DEST_PATH_ROOT/$OUTPUT_THEME_NAME"

if [ -f "$CONFIG_PATH" ]; then
    . "$CONFIG_PATH"
else
    echo "$CONFIG_PATH not found. Please reinstall to generate a default one." >&2
    exit 1
fi

darker () {
    darker_channel() {
        value="$1"
        light_delta="$2"
        result="$(echo "ibase=16; $value - $light_delta" | bc)"
        if [ "$result" -lt 0 ]; then
        result=0
        fi
        if [ "$result" -gt 255 ]; then
        result=255
        fi
        echo "$result"
    }

    hexinput="$(echo "$1" | tr '[:lower:]' '[:upper:]')"
    light_delta="${2-10}"

    a="$(echo "$hexinput" | cut -c-2 )"
    b="$(echo "$hexinput" | cut -c3-4)"
    c="$(echo "$hexinput" | cut -c5-6)"

    r="$(darker_channel "$a" "$light_delta")"
    g="$(darker_channel "$b" "$light_delta")"
    b="$(darker_channel "$c" "$light_delta")"

    printf '%02x%02x%02x\n' "$r" "$g" "$b"
}

mix () {
    mix_channel() {
        value1="$(printf '%03d' "0x$1")"
        value2="$(printf '%03d' "0x$2")"
        ratio="$3"
        result="$(echo "scale=0; ($value1 * 100 * $ratio + $value2 * 100 * (1 - $ratio)) / 100" | bc)"
        if [ "$result" -lt 0 ]; then
        result=0
        elif [ "$result" -gt 255 ]; then
        result=255
        fi
        echo "$result"
    }

    hexinput1="$(echo "$1"tr '[:lower:]' '[:upper:]')"
    hexinput2="$(echo "$2"tr '[:lower:]' '[:upper:]')"
    ratio="${3-0.5}"

    a="$(echo "$hexinput1" | cut -c-2)"
    b="$(echo "$hexinput1" | cut -c3-4)"
    c="$(echo "$hexinput1" | cut -c5-6)"
    d="$(echo "$hexinput2" | cut -c-2)"
    e="$(echo "$hexinput2" | cut -c3-4)"
    f="$(echo "$hexinput2" | cut -c5-6)"

    r="$(mix_channel "$a" "$d" "$ratio")"
    g="$(mix_channel "$b" "$e" "$ratio")"
    b="$(mix_channel "$c" "$f" "$ratio")"

    printf '%02x%02x%02x\n' "$r" "$g" "$b"
}

is_dark(){
    set -eu

	hexinput=$(echo "${1}" | tr '[:lower:]' '[:upper:]')
	half_darker=$(darker "${hexinput}" 88)
	if [ "${half_darker}" = "000000" ] ; then
        printf "false"
	else
        printf "true"
	fi
}


PATHLIST="
src/openbox-3
src/assets
src/gtk-2.0
src/gtk-3.0
src/gtk-3.20
src/qt5ct_palette.conf
src/qt6ct_palette.conf
src/xfwm4
src/metacity-1
src/unity
Makefile
src/index.theme
src/cinnamon
"
SVG_PREVIEWS="
gtk-3.0/thumbnail.svg
gtk-3.20/thumbnail.svg
metacity-1/thumbnail.svg
"

OPTION_GTK2_HIDPI=$(echo "${OPTION_GTK2_HIDPI-False}" | tr '[:upper:]' '[:lower:]')

# Migration:
HDR_BG=${HDR_BG-$MENU_BG}
HDR_FG=${HDR_FG-$MENU_FG}

ACCENT_BG=${ACCENT_BG-$SEL_BG}
HDR_BTN_BG=${HDR_BTN_BG-$BTN_BG}
HDR_BTN_FG=${HDR_BTN_FG-$BTN_FG}
WM_BORDER_FOCUS=${WM_BORDER_FOCUS-$SEL_BG}
WM_BORDER_UNFOCUS=${WM_BORDER_UNFOCUS-$HDR_BG}

GTK3_GENERATE_DARK=$(echo ${GTK3_GENERATE_DARK-"$(is_dark "$BG")"} | tr '[:upper:]' '[:lower:]')
UNITY_DEFAULT_LAUNCHER_STYLE=$(echo "${UNITY_DEFAULT_LAUNCHER_STYLE-False}" | tr '[:upper:]' '[:lower:]')

SPACING=${SPACING-3}
GRADIENT=${GRADIENT-0}
ROUNDNESS=${ROUNDNESS-2}
CINNAMON_OPACITY=${CINNAMON_OPACITY-1}
ROUNDNESS_GTK2_HIDPI=$(( ROUNDNESS * 2 ))

if [ "$(echo "$GRADIENT < 2" | bc)" ]; then
	GTK2_GRAD=$(echo "scale=2; $GRADIENT/2" | bc)
else
	GTK2_GRAD=1
fi
GTK2_GRAD_1=$(echo "1+$GTK2_GRAD" | bc)
GTK2_GRAD_2=$(echo "1-$GTK2_GRAD" | bc)
if expr "$GTK2_GRAD_1" : '-\?[0-9]\+$' >/dev/null; then
	GTK2_GRAD_TOP="$GTK2_GRAD_1".0
	GTK2_GRAD_BOTTOM="$GTK2_GRAD_2".0
else
	GTK2_GRAD_TOP=$GTK2_GRAD_1
	GTK2_GRAD_BOTTOM=$GTK2_GRAD_2
fi

OUTLINE_WIDTH=${OUTLINE_WIDTH-1}
BTN_OUTLINE_WIDTH=${BTN_OUTLINE_WIDTH-1}
BTN_OUTLINE_OFFSET=${BTN_OUTLINE_OFFSET--3}

INACTIVE_FG=$(mix ${FG} ${BG} 0.75)
INACTIVE_HDR_FG=$(mix ${HDR_FG} ${HDR_BG} 0.75)
INACTIVE_TXT_FG=$(mix ${TXT_FG} ${TXT_BG} 0.75)

light_folder_base_fallback="$(darker ${SEL_BG} -10)"
medium_base_fallback="$(darker ${SEL_BG} 37)"
dark_stroke_fallback="$(darker ${SEL_BG} 50)"

ICONS_LIGHT_FOLDER="${ICONS_LIGHT_FOLDER-$light_folder_base_fallback}"
ICONS_LIGHT="${ICONS_LIGHT-$SEL_BG}"
ICONS_MEDIUM="${ICONS_MEDIUM-$medium_base_fallback}"
ICONS_DARK="${ICONS_DARK-$dark_stroke_fallback}"

CARET1_FG="${CARET1_FG-$TXT_FG}"
CARET2_FG="${CARET2_FG-$TXT_FG}"
CARET_SIZE="${CARET_SIZE-0.04}"

TERMINAL_BACKGROUND=${TERMINAL_BACKGROUND:-$SEL_FG}
TERMINAL_COLOR4=${TERMINAL_COLOR4:-3f51b5}
TERMINAL_COLOR9=${TERMINAL_COLOR9:-f44336}
TERMINAL_COLOR10=${TERMINAL_COLOR10:-4caf50}
TERMINAL_COLOR11=${TERMINAL_COLOR11:-ef6c00}
TERMINAL_COLOR12=${TERMINAL_COLOR12:-03a9f4}


rm -rf "$DEST_PATH"
mkdir -p "$DEST_PATH"
echo "Building theme at $DEST_PATH"
cp -r "$SRC_PATH/src/index.theme" "$DEST_PATH"

for FILEPATH in $PATHLIST; do
	cp -r "$SRC_PATH/$FILEPATH" "$DEST_PATH"
done

cd "$DEST_PATH"
pwd
ls

for FILEPATH in $PATHLIST; do
	find "${FILEPATH#*src/}" -type f -exec sed -i'' \
		-e 's/%BG%/'"$BG"'/g' \
		-e 's/%FG%/'"$FG"'/g' \
		-e 's/%SEL_BG%/'"$SEL_BG"'/g' \
		-e 's/%SEL_FG%/'"$SEL_FG"'/g' \
		-e 's/%ACCENT_BG%/'"$ACCENT_BG"'/g' \
		-e 's/%TXT_BG%/'"$TXT_BG"'/g' \
		-e 's/%TXT_FG%/'"$TXT_FG"'/g' \
		-e 's/%HDR_BG%/'"$HDR_BG"'/g' \
		-e 's/%HDR_FG%/'"$HDR_FG"'/g' \
		-e 's/%BTN_BG%/'"$BTN_BG"'/g' \
		-e 's/%BTN_FG%/'"$BTN_FG"'/g' \
		-e 's/%HDR_BTN_BG%/'"$HDR_BTN_BG"'/g' \
		-e 's/%HDR_BTN_FG%/'"$HDR_BTN_FG"'/g' \
		-e 's/%WM_BORDER_FOCUS%/'"$WM_BORDER_FOCUS"'/g' \
		-e 's/%WM_BORDER_UNFOCUS%/'"$WM_BORDER_UNFOCUS"'/g' \
		-e 's/%ROUNDNESS%/'"$ROUNDNESS"'/g' \
		-e 's/%ROUNDNESS_GTK2_HIDPI%/'"$ROUNDNESS_GTK2_HIDPI"'/g' \
		-e 's/%OUTLINE_WIDTH%/'"$OUTLINE_WIDTH"'/g' \
		-e 's/%BTN_OUTLINE_WIDTH%/'"$BTN_OUTLINE_WIDTH"'/g' \
		-e 's/%BTN_OUTLINE_OFFSET%/'"$BTN_OUTLINE_OFFSET"'/g' \
		-e 's/%SPACING%/'"$SPACING"'/g' \
		-e 's/%GRADIENT%/'"$GRADIENT"'/g' \
		-e 's/%GTK2_GRAD_TOP%/'"$GTK2_GRAD_TOP"'/g' \
		-e 's/%GTK2_GRAD_BOTTOM%/'"$GTK2_GRAD_BOTTOM"'/g' \
		-e 's/%CINNAMON_OPACITY%/'"$CINNAMON_OPACITY"'/g' \
		-e 's/%INACTIVE_FG%/'"$INACTIVE_FG"'/g' \
		-e 's/%INACTIVE_TXT_FG%/'"$INACTIVE_TXT_FG"'/g' \
		-e 's/%INACTIVE_HDR_FG%/'"$INACTIVE_HDR_FG"'/g' \
		-e 's/%ICONS_DARK%/'"$ICONS_DARK"'/g' \
		-e 's/%ICONS_MEDIUM%/'"$ICONS_MEDIUM"'/g' \
		-e 's/%ICONS_LIGHT%/'"$ICONS_LIGHT"'/g' \
		-e 's/%ICONS_LIGHT_FOLDER%/'"$ICONS_LIGHT_FOLDER"'/g' \
		-e 's/%OUTPUT_THEME_NAME%/'"$OUTPUT_THEME_NAME"'/g' \
		-e 's/%CARET1_FG%/'"$CARET1_FG"'/g' \
		-e 's/%CARET2_FG%/'"$CARET2_FG"'/g' \
		-e 's/%CARET_SIZE%/'"$CARET_SIZE"'/g' \
		-e 's/%TERMINAL_BACKGROUND%/'"$TERMINAL_BACKGROUND"'/g' \
		-e 's/%TERMINAL_COLOR4%/'"$TERMINAL_COLOR4"'/g' \
		-e 's/%TERMINAL_COLOR9%/'"$TERMINAL_COLOR9"'/g' \
		-e 's/%TERMINAL_COLOR10%/'"$TERMINAL_COLOR10"'/g' \
		-e 's/%TERMINAL_COLOR11%/'"$TERMINAL_COLOR11"'/g' \
		-e 's/%TERMINAL_COLOR12%/'"$TERMINAL_COLOR12"'/g' \
		{} \; ;
done

if [ ${GTK3_GENERATE_DARK} != "true" ] ; then
	if [ -f ./gtk-3.0/scss/gtk-dark.scss ] ; then
		rm ./gtk-3.0/scss/gtk-dark.scss
	fi
	if [ -f ./gtk-3.20/scss/gtk-dark.scss ] ; then
		rm ./gtk-3.20/scss/gtk-dark.scss
	fi
fi
if [ ${OPTION_GTK2_HIDPI} = "true" ] ; then
	mv ./gtk-2.0/gtkrc.hidpi ./gtk-2.0/gtkrc
fi
if [ ${UNITY_DEFAULT_LAUNCHER_STYLE} = "true" ] ; then
	rm ./unity/launcher*.svg
fi

# run make
env MAKEFLAGS= make --jobs="$(nproc)" ${MAKE_OPTS}

# export qt5ct
qt5ct_colors_dir="${config_home}/qt5ct/colors/"
test -d "${qt5ct_colors_dir}" || mkdir -p "${qt5ct_colors_dir}"
mv ./qt5ct_palette.conf "${qt5ct_colors_dir}/${OUTPUT_THEME_NAME}.conf"

# export qt6ct
qt6ct_colors_dir="${config_home}/qt6ct/colors/"
test -d "${qt6ct_colors_dir}" || mkdir -p "${qt6ct_colors_dir}"
mv ./qt6ct_palette.conf "${qt6ct_colors_dir}/${OUTPUT_THEME_NAME}.conf"

rm -rf ./Makefile gtk-3.*/scss

for FILEPATH in $SVG_PREVIEWS; do
	rsvg-convert --format=png -o "$(echo "$FILEPATH" | sed -e 's/svg$/png/')" "$FILEPATH"
	rm "$FILEPATH"
done
